name: Build Flatpak bundle
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  flatpak-build:
    name: Build Flatpak Bundle
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: cz.muni.physics.munipack.flatpak
          manifest-path: cz.muni.physics.munipack.yaml
