name: Build Flatpak bundle
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  flatpak-build:
    name: Build Flatpak Bundle
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: cz.muni.physics.munipack-x86_64.flatpak
          manifest-path: cz.muni.physics.munipack.yaml
          upload-artifact: false

      - name: Uploadd Bundle
        uses: actions/upload-artifact@v4
        with:
          name: cz.muni.physics.munipack-x86_64
          path: cz.muni.physics.munipack-x86_64.flatpak
